<?xml version="1.0" encoding="utf-8"?><Database Name="ESDB" Class="ESDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=ESDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ESDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SeoText" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="OrderNumber" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </Type>
  </Table>
</Database>